require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 90
  IgnoredPatterns:
    - '\A(\s)*#'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/schema.rb"

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/jobs/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Naming/MemoizedInstanceVariableName:
  Exclude:
    - "app/structs/*"
