dist: xenial
services:
- postgresql
cache:
  bundler: true
  yarn: true
language: ruby
install:
- travis_retry nvm install 13.5.0
- bundle
- yarn
before_script:
- cp config/database.yml.travis config/database.yml
- rake db:setup
- RAILS_ENV=test bundle exec rails webpacker:compile
script:
- bundle exec rspec
- bundle exec rubocop --require rubocop-rails
deploy:
  provider: heroku
  api_key:
    secure: CYEdjR0YHmz5Gr+NWx0mAbnENyjKiyVxg5Eq6vC6aSNcTu6iBpssv+UaRSUrTIuPlTNm4d/lfkPac4EFSoZxNX2k/DSwBwb0Fn6T949CecV41H7Nosr+STVbsLWvLdIhtKrDRwIm7Qw3cyckf/XpvoBSWMKtq0tUtvYCk0sHcz8Sk4eLKazZsplS8pcFS200ZFOp7G1s3VmreNp00GUTHCn1XFyrAW2EneGuCcRcIDNAngX/jQ759E1he9GUB0nx1CIpRcV4oKYOAu9sv4Y0T9Zd782fj999CDxLQgkIabLkGDRrPCjPtaGCjMPbuf5g9oRdEkuZBOxBLdds+MVhPvoz6o8Ew48AtuE3ViVTTDRJo03Dw8KokmM3L9v0sqwvb8loBNrWbD43+cRErl0Tn+iqMWal6QuUEb/L8aceFWRyMuG33w6FK9UhWleIKR4s4lumC8qu0CFjXZ5o6kU/lp/8MwAPHdHfIzAARYwPfu5pINEsVwcmhEQ3zXLo/mAYjvofDvPgwpoYyFOPqwdJC8RrygDBDqm20Hh64xLpjyebrpMt8EeuaHPD0ESfQcYfDp0dmpKc8pEFuSiMTtLOHuKuCXPYps9WK7Iu7BS/6jJQalnXCbePGs83cstCrDuY0Bxvxu+EipBw+NFjwVtsQIhdQ45F6mTkNwGUCYZPlkw=
  before_deploy:
  - cp config/database.yml.heroku config/database.yml
  run:
  - rake db:migrate
  - rake cleanup
  on:
    all_branches: true
