dist: xenial
services:
  - postgresql
cache:
  bundler: true
  yarn: true
language: ruby
install:
  - travis_retry nvm install 13.5.0
  - bundle
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - rake db:setup
  - RAILS_ENV=test bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop --require rubocop-rails
