dist: xenial
cache:
  bundler: true
  yarn: true
language: ruby
global:
  - RAILS_ENV=test
install:
  - travis_retry nvm install 13.5.0
  - bundle
  - yarn
before_script:
  - RAILS_ENV=test bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop --require rubocop-rails
